export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const VERIFY_OTP = "VERIFY_OTP";
export const LOGIN_EMAIL = "LOGIN_EMAIL";
export const REGISTER_EMAIL = "REGISTER_EMAIL";
export const VERIFY_OTP_EMAIL = "VERIFY_OTP_EMAIL";
export const SET_LOCATION_ADDRESS = "SET_LOCATION_ADDRESS";
export const CLEAR_LOCATION_ADDRESS = "CLEAR_LOCATION_ADDRESS";
export const GET_TUTOR = "GET_TUTOR";
export const GET_THERAPIST = "GET_THERAPIST";
export const GET_TUTOR_BY_ID = "GET_TUTOR_BY_ID";
export const GET_IMAGES = "GET_IMAGES";
export const GET_YOGA_FOR_CATEGORY = "GET_YOGA_FOR_CATEGORY";
export const GET_MORNING_EVENING_TIMESLOT  = "GET_MORNING_EVENING_TIMESLOT";

export const UPDATE_USER = "UPDATE_USER";
export const ADD_PROFILE_PIC = "ADD_PROFILE_PIC";
export const DELETE_PROFILE_PIC = "DELETE_PROFILE_PIC";
export const GET_CHAKRA = "GET_CHAKRA";
export const GET_REFERRAL_DATA = "GET_REFERRAL_DATA";
export const GET_TUTOR_TIME_SLOT = "GET_TUTOR_TIME_SLOT";
export const CREATE_ORDER = "CREATE_ORDER";
export const VERIFY_PAYMENT = "VERIFY_PAYMENT";

export const GET_USER = "GET_USER";
export const ADD_ADDRESS = "ADD_ADDRESS";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const GET_ADDRESS_BY_ID = "GET_ADDRESS_BY_ID";

export const GET_ADDRESS = "GET_ADDRESS";




