export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const VERIFY_OTP = "VERIFY_OTP";
export const LOGIN_EMAIL = "LOGIN_EMAIL";
export const REGISTER_EMAIL = "REGISTER_EMAIL";
export const VERIFY_OTP_EMAIL = "VERIFY_OTP_EMAIL";
export const GET_INSTRUCTOR='GET_INSTRUCTOR';
export const PROFILE_PIC='PROFILE_PIC';
export const GET_USER_INSTRUCTOR = "GET_USER_INSTRUCTOR";
export const GET_VERSION = "GET_VERSION";
export const ADD_UPDATE_VERSION = "ADD_UPDATE_VERSION";

export const UPDATE_INSTRUCTOR='UPDATE_INSTRUCTOR';
export const GET_USER='GET_USER';

export const ADD_YOGA_STUDIO='ADD_YOGA_STUDIO';
export const GET_YOGA_STUDIO='GET_YOGA_STUDIO';
export const UPDATE_YOGA_STUDIO='UPDATE_YOGA_STUDIO';
export const GET_YOGA_STUDIO_BY_ID='GET_YOGA_STUDIO_BY_ID';
export const ADD_STUDIO_STEP_FIRST='ADD_STUDIO_STEP_FIRST';
export const UPDATE_STUDIO_STEP_FIRST='UPDATE_STUDIO_STEP_FIRST';
export const ADD_STUDIO_STEP_SECOND='ADD_STUDIO_STEP_SECOND';
export const UPDATE_STUDIO_STEP_SECOND='UPDATE_STUDIO_STEP_SECOND';
export const ADD_STUDIO_STEP_THIRD='ADD_STUDIO_STEP_THIRD';
export const DELETE_STUDIO='DELETE_STUDIO';
export const DELETE_STUDIO_TIME='DELETE_STUDIO_TIME';
export const DELETE_STUDIO_CONTACT='DELETE_STUDIO_CONTACT';
export const DELETE_STUDIO_IMAGE='DELETE_STUDIO_IMAGE';
export const SUBMIT_YOGA_STUDIO='SUBMIT_YOGA_STUDIO';
export const PUBLISH_YOGA_STUDIO='PUBLISH_YOGA_STUDIO';
export const SUBMIT_YS_CONTACT='SUBMIT_YS_CONTACT';
export const SUBMIT_YS_IMAGE='SUBMIT_YS_IMAGE';
export const SUBMIT_YS_TIME='SUBMIT_YS_TIME';

export const GET_CATEGORY='GET_CATEGORY';
export const GET_COURSE_TYPE='GET_COURSE_TYPE';
export const GET_COURSE_DURATION='GET_COURSE_DURATION';
export const GET_INSTITUTE='GET_INSTITUTE';
export const GET_UNIVERSITY='GET_UNIVERSITY';

export const GET_COURSE_DURATION_TYPE='GET_COURSE_DURATION_TYPE';

export const ADD_COURSE='ADD_COURSE';

export const ADD_QUALIFICATION='ADD_QUALIFICATION';
export const GET_QUALIFICATION='GET_QUALIFICATION';
export const UPDATE_QUALIFICATION='UPDATE_QUALIFICATION';
export const DELETE_QUALIFICATION='DELETE_QUALIFICATION';

export const ADD_EXPERIENCE='ADD_EXPERIENCE';
export const GET_EXPERIENCE='GET_EXPERIENCE';
export const DELETE_EXPERIENCE='DELETE_EXPERIENCE';
export const UPDATE_EXPERIENCE='UPDATE_EXPERIENCE';

export const ADD_HOME_TUTOR='ADD_HOME_TUTOR';
export const ADD_TUTOR_LOCATION='ADD_TUTOR_LOCATION';
export const ADD_TUTOR_PRICE='ADD_TUTOR_PRICE';

export const GET_TUTOR_QUALIFICATION='GET_TUTOR_QUALIFICATION';
export const GET_TUTOR='GET_TUTOR';
export const GET_TUTOR_BY_ID='GET_TUTOR_BY_ID';
export const ADD_TIME_SLOT='ADD_TIME_SLOT';
export const ADD_TUTOR_PHOTO='ADD_TUTOR_PHOTO';
export const DELETE_HOME_TUTOR='DELETE_HOME_TUTOR';
export const DELETE_TUTOR_LOCATION='DELETE_TUTOR_LOCATION';
export const DELETE_TUTOR_TIME_SLOT='DELETE_TUTOR_TIME_SLOT';
export const DELETE_TUTOR_IMAGE='DELETE_TUTOR_IMAGE';
export const SUBMIT_HOME_TUTOR='SUBMIT_HOME_TUTOR';
export const GET_SERVICE_AREA='GET_SERVICE_AREA';
export const GET_TUTOR_PRICE='GET_TUTOR_PRICE';
export const GET_HOMETUTOR_BY_ID='GET_HOMETUTOR_BY_ID';

export const GET_YOGA_FOR_CATEGORY='GET_YOGA_FOR_CATEGORY';

export const PUBLISH_HOME_TUTOR='PUBLISH_HOME_TUTOR'

export const UPDATE_HOME_TUTOR='UPDATE_HOME_TUTOR';
export const UPDATE_SERVICE_LOCATION='UPDATE_SERVICE_LOCATION';

export const UPDATE_TUTOR_TERM='UPDATE_TUTOR_TERM';
export const UPDATE_THERAPIST_TERM='UPDATE_THERAPIST_TERM';
export const UPDATE_YS_TERM='UPDATE_YS_TERM';

export const ADD_THERAPIST='ADD_THERAPIST';
export const GET_THERAPIST='GET_THERAPIST';
export const GET_THERAPIST_BY_ID='GET_THERAPIST_BY_ID';
export const ADD_THERAPIST_LOCATION='ADD_THERAPIST_LOCATION';
export const ADD_THERAPIST_PHOTO='ADD_THERAPIST_PHOTO';
export const ADD_THERAPIST_SLOT='ADD_THERAPIST_SLOT';
export const ADD_THERAPY='ADD_THERAPY';
export const SET_LOCATION_ADDRESS = "SET_LOCATION_ADDRESS";
export const CLEAR_LOCATION_ADDRESS = "CLEAR_LOCATION_ADDRESS";
export const GET_SERVICE_NOTIFICATION = "GET_SERVICE_NOTIFICATION";
export const ADD_AADHAR_VERIFICATION = "ADD_AADHAR_VERIFICATION";
export const GET_AADHAR_VERIFICATION = "GET_AADHAR_VERIFICATION";
export const UPDATE_AADHAR_VERIFICATION = "UPDATE_AADHAR_VERIFICATION";

export const ADD_BANK_VERIFICATION = "ADD_BANK_VERIFICATION";
export const UPDATE_BANK_VERIFICATION = "UPDATE_BANK_VERIFICATION";

export const GET_CHAKRA = "GET_CHAKRA";
export const GET_REFERRAL_DATA = "GET_REFERRAL_DATA";
export const GET_BANK_VERIFICATION = "GET_BANK_VERIFICATION";
export const GET_REFERRAL_DATA_SUCCESS = "GET_REFERRAL_DATA_SUCCESS";
export const GET_REFERRAL_DATA_FAILURE = "GET_REFERRAL_DATA_FAILURE";

